name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run git hooks
      run: |
        ./hooks/pre-commit
        ./hooks/pre-push
    - name: Run tests
      run: cargo test --verbose
